Using 'window.matchMedia' directly if  'useMediaQuery'  throws an error
For some reason 'useMediaQuery'  causes an error in FireFox which causes the dialog not to render. The error message is
TypeError: 'matchMedia' called on an object that does not implement interface Window.